line-length = 80

[lint]
select = ["B", "SIM", "I", "PD", "E", "W", "D", "F", "PL", "UP"]
ignore = ["D100", "D101", "D102", "D103", "D104", "D105", "D106", "D107"]

[lint.pydocstyle]
convention = "google"

[lint.isort]
known-first-party = ["autotrader"]